DEBUG 2020-08-27 20:44:41.660 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-27 20:44:41.661 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-27 20:44:41.661 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-27 20:44:41.661 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-27 20:44:41.662 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-27 20:44:41.662 UTC: 	 Loading CRAB configuration file.
ERROR 2020-08-27 20:44:41.663 UTC: 	 Error while loading CRAB configuration:
invalid syntax (crab_cfg.py, line 37)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-08-27 20:44:41.663 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
invalid syntax (crab_cfg.py, line 37)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-08-27 20:44:41.666 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
DEBUG 2020-08-27 20:45:32.497 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-27 20:45:32.498 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-27 20:45:32.498 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-27 20:45:32.498 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-27 20:45:32.499 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-27 20:45:32.499 UTC: 	 Loading CRAB configuration file.
ERROR 2020-08-27 20:45:32.506 UTC: 	 Error while loading CRAB configuration:
'function' object has no attribute 'section_'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-08-27 20:45:32.506 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
'function' object has no attribute 'section_'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-08-27 20:45:32.507 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
DEBUG 2020-08-27 20:48:47.036 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-27 20:48:47.036 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-27 20:48:47.036 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-27 20:48:47.037 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-27 20:48:47.037 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-27 20:48:47.037 UTC: 	 Loading CRAB configuration file.
ERROR 2020-08-27 20:48:47.042 UTC: 	 Error while loading CRAB configuration:
name 'config' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-08-27 20:48:47.042 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'config' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-08-27 20:48:47.044 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
DEBUG 2020-08-27 20:51:33.663 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-27 20:51:33.663 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-27 20:51:33.663 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-27 20:51:33.663 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-27 20:51:33.664 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-27 20:51:33.664 UTC: 	 Loading CRAB configuration file.
ERROR 2020-08-27 20:51:33.848 UTC: 	 Error while loading CRAB configuration:
name 'configuration' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-08-27 20:51:33.848 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'configuration' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-08-27 20:51:33.850 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
DEBUG 2020-08-27 20:52:47.781 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-27 20:52:47.782 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-27 20:52:47.782 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-27 20:52:47.782 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-27 20:52:47.783 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-27 20:52:47.783 UTC: 	 Loading CRAB configuration file.
ERROR 2020-08-27 20:52:47.784 UTC: 	 Error while loading CRAB configuration:
name 'configuration' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-08-27 20:52:47.784 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'configuration' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-08-27 20:52:47.786 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
DEBUG 2020-08-27 20:53:06.715 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-27 20:53:06.715 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-27 20:53:06.715 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-27 20:53:06.716 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-27 20:53:06.716 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-27 20:53:06.716 UTC: 	 Loading CRAB configuration file.
ERROR 2020-08-27 20:53:06.720 UTC: 	 Error while loading CRAB configuration:
name 'Configuration' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-08-27 20:53:06.720 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'Configuration' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-08-27 20:53:06.721 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
DEBUG 2020-08-27 20:53:53.740 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-27 20:53:53.740 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-27 20:53:53.740 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-27 20:53:53.741 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-27 20:53:53.742 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-27 20:53:53.742 UTC: 	 Loading CRAB configuration file.
ERROR 2020-08-27 20:53:53.746 UTC: 	 Invalid CRAB configuration: Parameter JobType.allowNonProductionCMSSW has been renamed to JobType.allowUndistributedCMSSW starting from CRAB v3.3.16; please change your configuration file accordingly.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-08-27 20:53:53.746 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 93, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter JobType.allowNonProductionCMSSW has been renamed to JobType.allowUndistributedCMSSW starting from CRAB v3.3.16; please change your configuration file accordingly.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-08-27 20:53:53.748 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
DEBUG 2020-08-27 22:21:03.924 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-27 22:21:03.924 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-27 22:21:03.924 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-27 22:21:03.924 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-27 22:21:03.925 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-27 22:21:03.925 UTC: 	 Loading CRAB configuration file.
ERROR 2020-08-27 22:21:04.286 UTC: 	 Invalid CRAB configuration: Parameter Data.outLFNDirbase is not known.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-08-27 22:21:04.286 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 93, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.outLFNDirbase is not known.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-08-27 22:21:04.288 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
DEBUG 2020-08-27 22:27:06.057 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-27 22:27:06.057 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-27 22:27:06.057 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-27 22:27:06.058 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-27 22:27:06.058 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-27 22:27:06.058 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-08-27 22:27:06.062 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-08-27 22:27:06.062 UTC: 	 Working area '/afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab_SMP_ww' already exists 
Please change the requestName in the config file
ERROR 2020-08-27 22:27:06.062 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab_SMP_ww' already exists 
Please change the requestName in the config file
INFO 2020-08-27 22:27:06.064 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
DEBUG 2020-08-27 22:30:01.080 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-27 22:30:01.081 UTC: 	 Running on: Linux lxplus753.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-27 22:30:01.081 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-27 22:30:01.081 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-27 22:30:01.082 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-27 22:30:01.082 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-08-27 22:30:01.083 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-08-27 22:30:01.083 UTC: 	 Working area '/afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab_SMP_ww' already exists 
Please change the requestName in the config file
ERROR 2020-08-27 22:30:01.083 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab_SMP_ww' already exists 
Please change the requestName in the config file
INFO 2020-08-27 22:30:01.085 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
DEBUG 2020-08-28 06:31:22.604 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-08-28 06:31:22.605 UTC: 	 Running on: Linux lxplus747.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-08-28 06:31:22.605 UTC: 	 Executing command: 'submit'
DEBUG 2020-08-28 06:31:22.605 UTC: 	 Found CRAB cache file /afs/cern.ch/user/h/hongyi/.crab3
INFO 2020-08-28 06:31:22.606 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-08-28 06:31:22.607 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-08-28 06:31:22.608 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-08-28 06:31:22.608 UTC: 	 Working area '/afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab_SMP_ww' already exists 
Please change the requestName in the config file
ERROR 2020-08-28 06:31:22.608 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab_SMP_ww' already exists 
Please change the requestName in the config file
INFO 2020-08-28 06:31:22.613 UTC: 	 Log file is /afs/cern.ch/user/h/hongyi/CMSSW_10_3_0/src/GenAnalyzer/genAnalyzer/python/crab.log
